<template>
  <v-container id="term-of-use" class="bg-tertiary-background fill-height align-start py-12" fluid>
    <v-row class="max-width ma-0">
      <v-col class="text-left pt-0" cols="12">
        <h1 class="text-h4 font-weight-bold text-secondary-text-color mb-4">Terms of Use</h1>
        <h2 class="text-body-1 font-weight-bold text-primary-text-color mb-2">1. Scope of These Terms and Conditions</h2>
        <p class="text-body-1 text-primary-text-color mb-4">
          <span>These Terms and Conditions are applicable to your access to and use of </span>
          <NuxtLink class="link-to text-primary" href="https://www.fastdoc.com" target="_blank">www.fastdoc.com</NuxtLink>
          <span> and all other websites and online applications operated by FastDoc LLC (collectively, “FastDoc”, “we,” “our,” “us”) that link to or incorporate these Terms and Conditions (the “Online Services”). Please read these Terms and Conditions carefully. Your access to and use of the Online Services and the information, materials, products, tools, and services available through the Online Services are subject to these Terms and Conditions, regardless of whether you possess or do not possess an account through the Online Services linked to your name and/or contact information (“Account”). By accessing or using the Online Services, you acknowledge that you understand and agree to be bound by these Terms and Conditions. If you do not understand or agree to be bound by these Terms and Conditions, do not access or use the Online Services.</span>
        </p>
        <p class="text-body-1 text-primary-text-color mb-4">When you use certain of the Online Services (e.g., FastDoc: Patient Portal, FastDoc: PreCheck, etc. ), we may provide you with additional terms and conditions relating to that specific Online Service, which will supplement the generally applicable terms of these Terms and Conditions. In the event of any inconsistency between these Terms and Conditions and any Online Service-specific terms and conditions, the Online Service-specific terms and conditions shall govern with respect to your access to and use of that Online Service.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">2. Privacy Statement</h2>
        <p class="text-body-1 text-primary-text-color mb-4">Our Privacy Statement describes how FastDoc collects information about you through the Online Services, and how we use, disclose, and protect that information.</p>
        
        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">3. Disclaimer of Content</h2>
        <p class="text-body-1 text-primary-text-color mb-4">The Online Services provide information about our company, and the products and services offered by it, including diagnostic health testing and services, data analysis, and clinical trials capabilities.</p>
        <p class="text-body-1 text-primary-text-color mb-4">If you are a patient or health care consumer, you should not use information found on the Online Services to replace a relationship with your physician or other health care professional and should not rely on that information as professional medical advice. Always seek the advice of your physician or other qualified healthcare provider concerning questions you have regarding a medical condition, and before starting, stopping, or modifying any treatment or medication. In the case of a health emergency, seek immediate assistance from emergency personnel. Never delay obtaining medical advice or disregard medical advice because of something you have or have not read on the Online Services.</p>
        <p class="text-body-1 text-primary-text-color mb-4">The information (including, without limitation, advice and recommendations) and services on the Online Services are intended solely as a general educational aid and are neither medical nor health care advice for any individual problem nor a substitute for medical or other professional advice and services from a qualified health care provider familiar with your medical history. Use of the Online Services does not create a doctor-patient relationship. No information contained in the Online Services is intended to be used for medical diagnosis or treatment. You acknowledge and agree that we have not represented that content provided through the Online Services has the ability to diagnose disease, prescribe treatment, or perform any other tasks that constitute the practice of medicine.</p>
        <p class="text-body-1 text-primary-text-color mb-4">While FastDoc attempts to keep all the information on the Online Services up-to-date, medical treatment and knowledge change quickly, and the Online Services should not be considered error-free or as a comprehensive source of all information on a particular topic. FastDoc makes no warranties or representations as to the accuracy of the content of the Online Services, and assumes no responsibility for any consequences relating directly or indirectly to any action or inaction you take based upon the information and material on the Online Services. Your use of the Online Services is subject to the additional disclaimers and caveats that may appear throughout these Terms and Conditions and the Online Services. You assume the entire risk of loss in using the Online Services and materials contained in the Online Services.</p>
        <p class="text-body-1 text-primary-text-color mb-4">Features and specifications of products or services described or depicted on the Online Services are subject to change at any time without notice.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">4. Copyright, Trademarks and other Intellectual Property</h2>
        <p class="text-body-1 text-primary-text-color mb-4">Copyright, trademark, patent, and other applicable laws protect the services and materials appearing on the Online Services. All materials on the Online Services may be accessed, downloaded, or printed for the noncommercial purpose of scientific or educational advancement or within the scope allowable by these Terms and Conditions. No other use of these materials may be made without express written permission of the operators of FastDoc. Any unauthorized use of the words or images on the Online Services may violate copyright laws, trademark laws, the laws of privacy and publicity, and civil and criminal statutes.</p>
        <p class="text-body-1 text-primary-text-color mb-4">The Online Services include material that is derived in whole or in part from materials that are copyrighted, including the format and layout of the Online Services. The copyrights are owned by FastDoc, or for licensed content, the content providers.</p>
        <p class="text-body-1 text-primary-text-color mb-4">The Online Services are owned by FastDoc LLC. None of the names, trademarks, service marks and logos of FastDoc appearing on the Online Services may be used in any advertising or publicity, or otherwise to indicate FastDoc’s sponsorship of or affiliation with any product or service, without express written permission of the operators of FastDoc.Nothing contained on the Online Services should be construed as granting, by implication, estoppel, waiver or otherwise, any license or right of use to any trademark displayed on the Online Services without the written permission of the owners and operators of FastDoc or the third party owner of the trademark, if any. The Online Services may contain other proprietary notices and copyright information, the terms of which must be observed and followed.</p>
        
        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">5. Right to Change Terms and Conditions</h2>
        <p class="text-body-1 text-primary-text-color mb-4">FastDoc may, at any time and from time to time, change these Terms and Conditions, in whole or in part. You agree to review these Terms and Conditions periodically. Any changes to these Terms and Conditions will be effective immediately upon the posting of the modified Terms and Conditions to the Online Services, and, if you possess an Account, by either providing notice of the changes to you when you log in to the Online Services or by sending notice of the changes to contact information that you have provided to us. You agree to comply with, and be bound by, the modified Terms and Conditions either (i) by continuing to use or access the Online Services after modified Terms and Conditions are posted to the Online Services, or (ii) if you possess an Account, by not requesting to terminate your Account within seven (7) calendar days after receiving a notice of the changes as described above.</p>
        
        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">6. Your Provision of Contact and Account Information to Us</h2>
        <p class="text-body-1 text-primary-text-color mb-4">When you provide information about yourself to us, including when you create an Account, you agree to: (a) provide accurate, current, and complete information about yourself, and not to provide information that attempts to impersonate another individual; and (b) maintain and promptly update such information to keep it accurate, current, and complete. If you provide any information that is untrue, inaccurate, or incomplete, or we have reasonable grounds to suspect that such information is untrue, inaccurate, or incomplete, we retain the right to suspend or terminate any Account you establish and/or to refuse any or all current or future use of the Online Services or any portion thereof. If the provided insurance information is inaccurate and/or incomplete causing the insurance claim to be rejected or only partially paid by the insurance company, FastDoc retains the right to charge you for the services directly.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">7. Communications from FastDoc</h2>
        <p class="text-body-1 text-primary-text-color mb-4">When you create an Account, or otherwise use the Services (including but not limited to Online Services), you may have the option to provide your contact information. By providing your contact information, you agree to receive recurring informational and/or marketing communications from FastDoc and/or our affiliates via email, phone call, and/or text message, including autodialed and prerecorded calls and messages.</p>
        <p class="text-body-1 text-primary-text-color mb-4">If you have any questions about receiving communications from us, please contact us using the information in the “Contact Information” section below. To unsubscribe from marketing emails, click the “Unsubscribe” link at the bottom of the email you received from us. To unsubscribe from calls, follow the instructions provided in the phone message.</p>
        <p class="text-body-1 text-primary-text-color mb-4">Even if you unsubscribe from marketing communications, if any, we may still send communications related to lab services such as appointment confirmations and reminders, test result and invoice notifications or other similar information.</p>
        <p class="text-body-1 text-primary-text-color mb-4">The following provisions apply specifically to SMS text messages, if available for your account:</p>
        <ol class="text-body-1 text-primary-text-color mb-4 ml-10" type="a">
          <li class="mb-2">When you order a test kit and provide your phone number, you consent to receiving SMS messages regarding your order status, delivery reminders, results notifications, billing-related communications, and any other future communication from FastDoc.</li>
          <li class="mb-2">You can opt out of receiving SMS at any time by texting “STOP”. You will be notified once you have successfully opted out. If you want to start receiving SMS again, please reply with “START” and we will start sending SMS messages to you again.</li>
          <li class="mb-2">If at any time you need help you can text us with the message “HELP” or reach out to our customer support via the website chat.</li>
          <li class="mb-2">We are able to deliver messages to the following mobile phone carriers: Major carriers: AT&T, Verizon Wireless, Sprint, T-Mobile, MetroPCS, U.S. Cellular, Alltel, Boost Mobile, Nextel, and Virgin Mobile. Minor carriers: Alaska Communications Systems (ACS), Appalachian Wireless (EKN), Bluegrass Cellular, Cellular One of East Central IL (ECIT), Cellular One of Northeast Pennsylvania, Cincinnati Bell Wireless, Cricket, Coral Wireless (Mobi PCS), COX, Cross, Element Mobile (Flat Wireless), Epic Touch (Elkhart Telephone), GCI, Golden State, Hawkeye (Chat Mobility), Hawkeye (NW Missouri), Illinois Valley Cellular, Inland Cellular, iWireless (Iowa Wireless), Keystone Wireless (Immix Wireless/PC Man), Mosaic (Consolidated or CTC Telecom), Nex-Tech Wireless, NTelos, Panhandle Communications, Pioneer, Plateau (Texas RSA 3 Ltd), Revol, RINA, Simmetry (TMP Corporation), Thumb Cellular, Union Wireless, United Wireless, Viaero Wireless, and West Central (WCC or 5 Star Wireless). ***Carriers are not liable for delayed or undelivered messages***</li>
          <li class="mb-2">As always, message and data rates may apply for any messages sent to you from a FastDoc short code and to us from you. If you have any questions about your text plan or data plan, it is best to contact your wireless provider. For all questions about the services provided by this short code, please contact us using the information in the “Contact Information” section below.</li>
          <li class="mb-2">
            <span>If you have any questions regarding privacy, please read our </span>
            <NuxtLink class="link-to text-primary" :to="{ path: '/privacy-policy' }">Privacy Policy</NuxtLink>
            <span>.</span>
          </li>
        </ol>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">8. Use of the Online Services by Health Care Providers and Health Plans</h2>
        <p class="text-body-1 text-primary-text-color mb-4">If you are a health care provider or a health plan, you represent and warrant that when using the Online Services you will comply with all applicable laws and regulations, including the Health Insurance Portability and Accountability Act and its implementing regulations and other federal and state privacy and data security laws, and you will not provide any information, including protected health information, to us for which you do not have the required authorizations or consents.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">9. User-Provided Content</h2>
        <p class="text-body-1 text-primary-text-color mb-4">You understand that all information, data, or other materials that you and other users of the Online Services upload, post, transmit, publish, display, or otherwise make available through the Online Services, including information you share with or make available to other users of the Online Services (“User-Provided Content”), are the sole responsibility of you or the person from whom such User-Provided Content originated. This means that you, and not us, are responsible for all User-Provided Content that you upload, post, transmit, publish, display, or otherwise make available through the Online Services. We do not control the User-Provided Content posted and, as such, do not guarantee the accuracy, integrity, or quality of any User-Provided Content. Furthermore, the User-Provided Content is for informational purposes only and is not intended to be a substitute for professional medical advice, diagnosis, or treatment. You understand that by using the Online Services, you may be exposed to User-Provided Content that is offensive, indecent, or objectionable. Under no circumstances will we be liable in any way for or related to any User-Provided Content, including, but not limited to, for any errors or omissions in any User-Provided Content, or for any loss or damage of any kind incurred as a result of the publication or use of or reliance on any User-Provided Content uploaded, posted, transmitted, published, displayed, or otherwise made available through the Online Services.</p>
        <p class="text-body-1 text-primary-text-color mb-4">By uploading, posting, transmitting, publishing, displaying, or otherwise making available User-Provided Content through the Online Services, you represent and warrant that:</p>
        <ul class="text-body-1 text-primary-text-color mb-4 ml-10">
          <li class="mb-2">you own or control all rights, title, and interests to such User-Provided Content;</li>
          <li class="mb-2">all “moral rights” that you may have in such User-Provided Content have been voluntarily waived by you;</li>
          <li class="mb-2">you have the right to grant the licenses granted under these Terms and Conditions;</li>
          <li class="mb-2">all User-Provided Content that you post: (i) is accurate; (ii) does not violate these Terms and Conditions; (iii) will not conflict with, result in a breach or violation of any terms or provisions of, or constitute a default under any contract or agreement to which you are currently bound or will become bound in the future; (iv) does not and will not violate any law, and (v) will not cause injury to any person or entity; and</li>
          <li class="mb-2">you are at least 13 years old.</li>
        </ul>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">10. Your Grant of License to FastDoc for User-Provided Content</h2>
        <p class="text-body-1 text-primary-text-color mb-4">By uploading, posting, transmitting, publishing, displaying, or otherwise making available User-Provided Content, you grant us a worldwide, perpetual, non-exclusive, royalty-free license (with the right to sub-license) to use, reproduce, display, perform, adapt, modify, publish, create derivative works from, or distribute such User-Provided Content in whole or in part in any form, medium, or technology (now known or later developed) without compensation to you, including but not limited to, in any unaffiliated third party content and in our or their publications, marketing material, and advertisements. We may modify or adapt User-Provided Content, including in order to transmit, display, or distribute it over networks and to conform to the requirements of networks, services, or other media. We or others may, in our sole discretion, cite to your name or other identifier you provided when posting User-Provided Content. You represent and warrant that our publication and use of your User-Provided Content will not infringe or violate the intellectual property or other rights of any third party.</p>
        <p class="text-body-1 text-primary-text-color mb-4">This section does not apply to any protected health information that you upload, post, transmit, publish, display, or otherwise make available through the Online Services.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">11. FastDoc’s Discretion to Use User-Provided Content</h2>
        <p class="text-body-1 text-primary-text-color mb-4">User-Provided Content that you upload, post, transmit, publish, display, or otherwise make available through the Online Services may be used by FastDoc in accordance with our Privacy Statement. FastDoc reserves the right to change, condense, delete, or refuse to post any User-Provided Content on the Online Services in its sole discretion. None of the User-Provided Content that you submit shall be subject to any obligation of confidence on the part of FastDoc, its agents, partners, or third-party service providers and their respective directors, officers, and employees.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">12. Your Conduct</h2>
        <p class="text-body-1 text-primary-text-color mb-4">You agree to comply with all laws, rules, and regulations applicable to your use of the Online Services. In addition, you agree not to:</p>
        <p class="text-body-1 text-primary-text-color mb-4">upload, post, email, transmit, or otherwise make available any User-Provided Content that is known by you to be false, inaccurate, or misleading;</p>
        <p class="text-body-1 text-primary-text-color mb-4">upload, post, email, transmit, or otherwise make available any User-Provided Content that violates any law, statute, ordinance, or regulation (including, but not limited to, those governing export control, consumer protection, unfair competition, anti-discrimination, or false advertising);</p>
        <p class="text-body-1 text-primary-text-color mb-4">upload, post, email, transmit, or otherwise make available any User-Provided Content that is, or may reasonably be considered to be, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another’s privacy, hateful, or racially, ethnically or otherwise objectionable, or that harms minors in any way;</p>
        <p class="text-body-1 text-primary-text-color mb-4">forge headers or otherwise manipulate identifiers in order to disguise the origin of any User-Provided Content transmitted in connection with the Online Services;</p>
        <p class="text-body-1 text-primary-text-color mb-4">upload, post, email, transmit, or otherwise make available any User-Provided Content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, or proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</p>
        <p class="text-body-1 text-primary-text-color mb-4">upload, post, email, transmit, or otherwise make available any User-Provided Content that infringes any patent, trademark, trade secret, copyright, right of publicity, or other proprietary right of any party;</p>
        <p class="text-body-1 text-primary-text-color mb-4">upload, post, email, transmit, or otherwise make available any unsolicited or unauthorized advertising, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation;</p>
        <p class="text-body-1 text-primary-text-color mb-4">upload, post, email, transmit, or otherwise make available any material that contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment;</p>
        <p class="text-body-1 text-primary-text-color mb-4">take any action that interferes with the proper working of the Online Services, compromises the security of the Online Services, or otherwise damages the Online Services or any materials and information available through the Online Services</p>
        <p class="text-body-1 text-primary-text-color mb-4">attempt to gain unauthorized access to any portion or feature of the Online Services, to any other systems or networks connected to the Online Services, to any of our servers, or to any of the services offered on or through the Online Services, including but not limited to by hacking, password “mining”, or any other unauthorized means;</p>
        <p class="text-body-1 text-primary-text-color mb-4">probe, scan, or test the vulnerability of the Online Services or any network connected to the Online Services or bypass the authentication measures on the Online Services or any network connected to the Online Services;</p>
        <p class="text-body-1 text-primary-text-color mb-4">use any automated means to collect information or content from or otherwise access the Online Services, including but not limited to through the use of technical tools known as robots, spiders, or scrapers, without our prior permission;</p>
        <p class="text-body-1 text-primary-text-color mb-4">harvest or otherwise collect and store information about other users of the Online Services, including e-mail addresses;</p>
        <p class="text-body-1 text-primary-text-color mb-4">install any software, file, or code that is not authorized by the user of a computer or mobile device or that assumes control of all or any part of the processing performed by a computer or mobile device without the authorization of the user of the computer or mobile device; or</p>
        <p class="text-body-1 text-primary-text-color mb-4">interfere with or disrupt the operation of the Online Services or server networks connected to the Online Services, or disobey any requirements, procedures, policies, or regulations of networks connected to the Online Services.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">13. Third Party-Owned Content and Links to Third Party Owned-Websites or Online Applications</h2>
        <p class="text-body-1 text-primary-text-color mb-4">The Online Services may contain third party-owned content (e.g., articles, data feeds, abstracts, etc.) and may also include hypertext links to third party-owned websites and online applications. We provide such third party-owned content and links as a courtesy to our users. We have no control over any third party-owned websites or online applications or third-party owned content referenced on, linked to from, accessed by, or available on the Online Services and, therefore, we do not endorse, sponsor, recommend, or otherwise accept any responsibility for such third party-owned websites or online applications (or the availability of such websites or online applications) or third-party owned content. IN PARTICULAR, WE DO NOT ACCEPT ANY LIABILITY ARISING OUT OF ANY ALLEGATION THAT ANY THIRD PARTY-OWNED CONTENT (WHETHER PUBLISHED ON THE ONLINE SERVICES, OR ANY OTHER WEBSITE OR ONLINE APPLICATION) INFRINGES THE INTELLECTUAL PROPERTY RIGHTS OF ANY PERSON OR ANY LIABILITY ARISING OUT OF ANY INFORMATION OR OPINION CONTAINED IN SUCH third-party owned content OR ON ANY THIRD PARTY-OWNED website or online application LINKED TO FROM THE ONLINE SERVICES.</p>
        <p class="text-body-1 text-primary-text-color mb-4">You acknowledge and agree that we are not responsible or liable for the accuracy; collection, use, disclosure, or protection of information; copyright compliance; legality; decency; or any other aspect of third party-owned websites or online applications that are linked to from the Online Services or the content displayed on or through them. If you visit third party-owned websites or online applications by clicking links on the Online Services, we encourage you to consult the privacy policy and the terms and conditions of each such website or online application you visit.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">14. Links to the Online Services</h2>
        <p class="text-body-1 text-primary-text-color mb-4">You should not link to the Online Services, nor use FastDoc’s name, trademark, logos, or otherwise refer to FastDoc in any public communications without first obtaining FastDoc’s advance written consent.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">15. Advertising and Sponsorships</h2>
        <p class="text-body-1 text-primary-text-color mb-4">We do not accept paid advertisements or sponsorships on the Online Services.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">16. Information, News, and Press Releases</h2>
        <p class="text-body-1 text-primary-text-color mb-4">The Online Services may contain information about FastDoc, such as news and press releases. You acknowledge that we have no duty or obligation to maintain the accuracy of, or update any such information, and agree that your reliance on any such information is at your own risk.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">17. Registration and Passwords</h2>
        <p class="text-body-1 text-primary-text-color mb-4">The Online Services may permit or require you to register or obtain a password prior to permitting you to access certain portions of the Online Services. You acknowledge and agree that you are responsible for maintaining the confidentiality of your Kit ID, login ID and password, and for all uses of your Kit ID, login ID, password, and/or Account. You agree to notify us immediately of any unauthorized use of your Kit ID, login ID, password, or Account, or any other breach of security involving access to the Online Services through your Account. You acknowledge that you may be held liable for any loss or harm incurred by us or any other person or entity due to someone else using your Kit ID, login ID, password, or Account as a result of your failing to keep your Account information secure and confidential.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">18. Operation of the Online Services</h2>
        <p class="text-body-1 text-primary-text-color mb-4">We reserve the right to do any of the following, at any time, at our sole discretion, with or without notice: (i) modify, suspend, or terminate operation of or your access to the Online Services, or any portion of the Online Services, including but not limited to for your violation of these Terms and Conditions; (ii) modify or change the Online Services, or any portion of the Online Services; and (iii) interrupt the regular operation of the Online Services, or any portion of the Online Services, as necessary to perform routine or non-routine maintenance, to correct errors, or to make other changes to the Online Services.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">19. Order Regulations</h2>
        <p class="text-body-1 text-primary-text-color mb-4">All products being ordered online are regulated by strict governmental regulations and CDC guidelines. If the patient fails to use the test kit or fails to return the sample back to FastDoc for testing within 7 days from the date of delivery, then FastDoc retains the right to charge the patient directly for the testing services and for other associated costs and related charges as applicable.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">20. Disclaimer of Warranty; Limitation of Liability</h2>
        <p class="text-body-1 text-primary-text-color mb-4">THE ONLINE SERVICES AND ALL MATERIALS, INFORMATION, SOFTWARE, PRODUCTS, TOOLS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE ONLINE SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. FastDoc AND ITS SUPPLIERS DISCLAIM ALL EXPRESS AND IMPLIED WARRANTIES WITH REGARD TO THE ONLINE SERVICES AND ALL MATERIALS, INFORMATION, SOFTWARE, PRODUCTS, TOOLS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE ONLINE SERVICES, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. YOUR USE OF THE ONLINE SERVICES IS AT YOUR OWN RISK. ACCESS TO THE ONLINE SERVICES MAY BE INTERRUPTED AND THE MATERIALS, INFORMATION, SOFTWARE, PRODUCTS, TOOLS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE ONLINE SERVICES MAY NOT BE ERROR-FREE. NONE OF FastDoc, ITS SUPPLIERS, OR ANYONE ELSE INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE ONLINE SERVICES OR THE MATERIALS, INFORMATION, SOFTWARE, PRODUCTS, TOOLS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE ONLINE SERVICES WARRANTS THAT THE MATERIALS, INFORMATION, SOFTWARE, PRODUCTS, TOOLS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE ONLINE SERVICES ARE ACCURATE, RELIABLE, COMPLETE, USEFUL, OR CORRECT; THAT THE ONLINE SERVICES WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE ONLINE SERVICES ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. PLEASE NOTE THAT SOME JURISDICTIONS MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. CHECK YOUR LOCAL LAWS FOR ANY RESTRICTIONS OR LIMITATIONS REGARDING THE EXCLUSION OF IMPLIED WARRANTIES.</p>
        <p class="text-body-1 text-primary-text-color mb-4">UNDER NO CIRCUMSTANCES SHALL FastDoc, ITS SUPPLIERS, OR ANYONE ELSE INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE ONLINE SERVICES OR THE MATERIALS, INFORMATION, SOFTWARE, PRODUCTS, TOOLS, AND SERVICES INCLUDED IN OR AVAILABLE THROUGH THE ONLINE SERVICES BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND, INCLUDING LOSS OF DATA, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF, OR INABILITY TO USE, THE ONLINE SERVICES. THIS LIMITATION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN THE EVENT SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF DAMAGES TO THE EXTENT INDICATED ABOVE, OUR LIABILITY IN SUCH JURISDICTIONS SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>
        <p class="text-body-1 text-primary-text-color mb-4">YOU ACKNOWLEDGE AND AGREE THAT THE LIMITATIONS SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THIS AGREEMENT AND THE ONLINE SERVICES WOULD NOT BE PROVIDED TO YOU ABSENT SUCH LIMITATIONS.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">21. Indemnification</h2>
        <p class="text-body-1 text-primary-text-color mb-4">You agree to indemnify, defend, and hold harmless FastDoc and its suppliers, and their respective affiliates, subsidiaries, employees, officers, directors, agents, contractors, servants, insurers, and representatives from any liability, loss, claim, suit, damage, judgment and expense (including reasonable attorneys’ fees and expenses) that arise out of or are related to any User-Provided Content you submit, post, transmit, or make available through the Online Services, your violation of these Terms and Conditions, your use or misuse of the Online Services, or your violation of any third-party rights.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">22. Severability</h2>
        <p class="text-body-1 text-primary-text-color mb-4">If any provision of these Terms and Conditions is held invalid or unenforceable by any court of competent jurisdiction, the other provisions of these Terms and Conditions shall remain in full force and effect. Any provision of these Terms and Conditions held invalid or unenforceable only in part or degree will remain in full force and effect to the extent not held invalid or unenforceable. The parties further agree to replace such invalid or unenforceable provision of these Terms and Conditions with a valid and enforceable provision that will achieve, to the extent possible, the economic, business, and other purposes of such invalid or unenforceable provision.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">23. Applicable Law</h2>
        <p class="text-body-1 text-primary-text-color mb-4">These Terms and Conditions and the resolution of any dispute related to these Terms and Conditions shall be construed in accordance with the laws of the State of New York. Any dispute between FastDoc and you related to these Terms and Conditions shall be resolved exclusively by the state and federal courts of the State of New York.</p>
        <p class="text-body-1 text-primary-text-color mb-4">The Online Services can be accessed from the United States and other countries worldwide. Since the laws of each State or country may differ, you agree that the statutes and laws of the State of New York, without regard to any principles of conflicts of law, will apply to all matters relating to your access to or use of the Online Services.</p>
        <p class="text-body-1 text-primary-text-color mb-4">FastDoc makes no representation that material on the Online Services is appropriate or available for use in other locations, and accessing this information from territories where the content is illegal is prohibited. Those who choose to access the Online Services from other locations do so by their own initiative and are responsible for compliance with local laws.</p>
        <p class="text-body-1 text-primary-text-color mb-4">The information available on this website is subject to U.S. export control laws. The Online Services may not be accessed from Cuba, the Crimea region, Iran, North Korea, Syria, or from any other destination embargoed by the United States.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">24. Assignment of Benefits</h2>
        <p class="text-body-1 text-primary-text-color mb-4">You hereby authorize your Insurance Company to pay by check made payable and mailed directly to: FastDoc LLC, LLC for the medical and surgical benefits allowable, and otherwise payable to you under your current insurance policy, as payment toward the total charges for the services rendered. You understand that as a courtesy to yourself, FastDoc LLC, LLC will file a claim with your insurance company on your behalf. However, You are financially responsible for, and hereby do agree to pay, in a current manner, any charges not covered by the insurance payment. If it is necessary to file a formal collection action, You agree to pay all costs, including reasonable attorney’s fees incurred by FastDoc LLC, LLC in the collection of the outstanding fees. Actual Plan Benefits cannot be determined until the claim is received by your insurance company and is based upon their determination of medical necessity. The information received from the above stated is not a guarantee of payment.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">25. Appointment of Representative</h2>
        <p class="text-body-1 text-primary-text-color mb-4">By using FastDoc LLC LLC services and this website, you are appointing FastDoc LLC LLC to act as your representative in connection with your claim or asserted right under Title XVIII of the Social Security Act (the “Act”) and related provisions of Title XI of the Act. You authorize FastDoc LLC LLC  to make any request; to present or to elicit evidence; to obtain appeals information; and to receive any notice in connection with your claim, appeal, grievance or request wholly in your stead. You understand that personal medical information related to the request may be disclosed to FastDoc LLC LLC.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">26. Sharing of Confidential Information</h2>
        <p class="text-body-1 text-primary-text-color mb-4">By using our website and services, you acknowledge and agree that FastDoc LLC LLC may share your otherwise confidential information with its affiliated entities, FastDoc LLC and FastDoc Inc. This information may include, but is not limited to, personal identification details, medical records, financial information, and other data that you provide or that we collect during the course of your use of our services. The sharing of such information is intended to enhance the coordination and quality of the services we provide, facilitate integrated healthcare solutions, and improve our overall operational efficiency.</p>
        <p class="text-body-1 text-primary-text-color mb-4">FastDoc LLC LLC, FastDoc LLC, and FastDoc Inc. are committed to maintaining the confidentiality, integrity, and security of your information. We employ robust security measures and adhere to applicable laws and regulations, including but not limited to HIPAA, to protect your confidential information from unauthorized access, use, or disclosure. However, you acknowledge and agree that the sharing of information among these entities is necessary for the aforementioned purposes and consent to such sharing by continuing to use our website and services.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">27. Termination</h2>
        <p class="text-body-1 text-primary-text-color mb-4">These Terms and Conditions are effective unless and until modified as noted above, or terminated, at any time, by FastDoc.</p>

        <h2 class="text-body-1 font-weight-bold text-primary-text-color mt-8 mb-2">28. Contact Information</h2>
        <p class="text-body-1 text-primary-text-color mb-4">FastDoc is headquartered in New York, New York, in the United States of America.</p>
        <p class="text-body-1 mb-4">
          <NuxtLink class="link-to text-primary" href="mailto:contact@fastdoc.com">contact@fastdoc.com</NuxtLink>
        </p>
        <p class="text-body-1 text-primary-text-color mb-4">FastDoc LLC</p>
        <p class="text-body-1 text-primary-text-color mb-4">1178 Broadway</p>
        <p class="text-body-1 text-primary-text-color mb-4">New York, NY 10001</p>
        <p class="text-body-1 text-primary-text-color mb-4">While we make every effort to respond to all correspondence within 1 business week, we cannot guarantee a response to every electronic communication.</p>
        <p class="text-body-1 text-primary-text-color">These Terms and Conditions were last updated on: August 7, 2024</p>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts" setup>
  import { VContainer, VRow, VCol } from 'vuetify/components';
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss" scoped></style>